[workspace]

members = [
    "android",
    "domain",
    "repository",
    "graphql",
    "server",
    "service",
    "util",
    "graphql/core",
    "graphql/types",
    "graphql/requisition",
    "graphql/requisition_line",
    "graphql/stocktake",
    "graphql/stocktake_line",
    "graphql/invoice",
    "graphql/invoice_line",
    "graphql/location",
    "graphql/general_queries",
    "graphql/general_mutations",
    "graphql/batch_mutations",
]
