[package]
name = "service"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]

repository = { path = "../repository" }
util = { path = "../util" }
anymap = "0.12"
anyhow = "1.0.44"
bcrypt = "0.12.0"
chrono = { version = "0.4", features = ["serde"] }
jsonwebtoken = "8.0.1"
log = "0.4.14"
serde = "1.0.126"
serde_json = "1.0.66"

[dev-dependencies]
actix-rt = "2.6.0"

[features]
default = ["sqlite"]
sqlite = ["repository/sqlite"]
postgres = ["repository/postgres"]
