[package]
name = "service"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
repository = { path = "../repository" }
util = { path = "../util" }

anymap = "0.12"
anyhow = "1.0.44"
bcrypt = "0.12.0"
chrono = { version = "0.4", features = ["serde"] }
jsonschema = "0.16.0"
jsonwebtoken = "8.0.1"
log = "0.4.14"
reqwest = { version = "0.11", features = ["json"] } 
serde = "1.0.126"
serde_json = "1.0.66"
tera = "1"
tokio = "1.17.0"
headless_chrome = "0.9"
failure = "0.1.8"

[dev-dependencies]
actix-rt = "2.6.0"
assert-json-diff = "2.0.1"
httpmock= "0.6.6"

[features]
default = ["sqlite"]
sqlite = ["repository/sqlite"]
postgres = ["repository/postgres"]
