[package]
name = "android"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"
name = "remote_server_android"

[dependencies]
repository = { path = "../repository" }
server = { path = "../server" }

actix-web = { version= "3.3.2", features = ["openssl"] } 
android_logger = "0.10.1"
jni = { version = "0.19.0"}
log = "0.4.14"
once_cell = "1.9.0"
tokio = { version = "1.17.0", features = ["macros" ] }

[features]
default = ["repository/sqlite", "server/android"]
