[package]
name = "server"
version = "0.1.0"
authors = ["will"]
edition = "2018"
default-run = "remote_server"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "remote_server"

[dependencies]

graphql = { path = "../graphql" }
graphql_core = { path = "../graphql/core" }
graphql_types = { path = "../graphql/types" }
repository = { path = "../repository" }
service = { path = "../service" }
util = { path = "../util" }

actix-cors = "0.6.1"
actix-web = { version= "4.0.1", features = ["openssl"] } 
actix-files = "0.6.0"
openssl = { version = "0.10", features = ["v110"] }
anyhow = "1.0.44"
config = "0.11.0"
chrono = { version = "0.4", features = ["serde"] }
env_logger = "0.8.3"
log = "0.4.14"
reqwest = { version = "0.11", features = ["json"] } 
serde = "1.0.126"
serde_json = "1.0.66"
tokio = { version = "1.17.0", features = ["macros" ] }
thiserror = "1"

[dev-dependencies]
actix-rt = "2.6.0"
assert-json-diff = "2.0.1"
httpmock = "0.6"

[features]
default = ["repository/sqlite"]
postgres = ["repository/postgres"]
android = ["repository/sqlite", "openssl/vendored"]
