[package]
name = "server"
version = "0.1.0"
authors = ["will"]
edition = "2018"
default-run = "remote_server"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "remote_server"

[dependencies]
domain = { path = "../domain" }
graphql = { path = "../graphql" }
repository = { path = "../repository" }
service = { path = "../service" }
util = { path = "../util" }

actix-cors = "0.5.4"
actix-web = { version= "3.3.2", features = ["openssl"] } # Versions >=v4 depend on Tokio v1.
openssl = { version = "0.10", features = ["v110"] }
anyhow = "1.0.44"
config = "0.11.0"
env_logger = "0.8.3"
log = "0.4.14"
reqwest = { version = "0.10", features = ["json"] } # Versions >=0.11 depend on Tokio v1.
serde = "1.0.126"
serde_json = "1.0.66"
tokio = { version = "0.2", features = ["macros" ] } # Bumping to v1 requires actix-web >=v4 and reqwest >=0.11.
thiserror = "1"

[dev-dependencies]
actix-rt = "1.1.1" # for Tokio 0.2
assert-json-diff = "2.0.1"
chrono = { version = "0.4", features = ["serde"] }
graphql_client = "0.10.0"
httpmock = "0.6"

[features]
default = ["repository/sqlite"]
postgres = ["repository/postgres"]
