[package]
name = "util"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
sha2 = "0.10.2"
uuid = { version = "1.0.0", features = ["v4"] }
chrono = "0.4.19"
serde = "1.0.126"
serde_json = "1.0.66"
