[package]
name = "report_builder"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/cli.rs"
name = "report_builder"
test = false
bench = false

[dependencies]
service = { path = "../service" }

anyhow = "1.0.56"
clap = { version = "3.1.8", features = ["derive"] }
serde = "1.0.126"
serde_json = "1.0.66"
serde_yaml = "0.8.23"
log = "0.4.16"
reqwest = { version = "0.11.10", features = ["blocking"] }
regex = "1.5.5"
