server:
  port: 8000
  # debug_no_access_control: true # enable this if you want to ignore API authorisation (dummy user will be used for all operations)
  cors_origin: http://localhost:3003 #Used to set the allowed Origin in Cross Origin Requst Security
sync:
  url: "http://localhost:2048"
  username: "username"
  password_sha256: "hashed_password"
  interval_sec: 300
  central_server_site_id: 1
  site_id: 2
  site_hardware_id: ""
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "omsupply-database"
auth:
  token_secret: "token-secret"
