server:
  port: 8000
  # debug_no_access_control: true # enable this if you want to ignore API authorisation (dummy user will be used for all operations)
  # debug_cors_permissive: true # enable this to allow any origin for development purposes
  cors_origins: [
      http://localhost:3003,
      https://demo-open.msupply.org,
      https://graphiql-online.com,
    ] # Used to set the allowed Origin in Cross Origin Requst Security
sync:
  url: "http://localhost:2048"
  username: "demo"
  password_sha256: "d74ff0ee8da3b9806b18c877dbf29bbde50b5bd8e4dad7a3a725000feb82e8f1"
  interval_sec: 300
  central_server_site_id: 1
  site_id: 2
  site_hardware_id: ""
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "omsupply-database"
