server:
  port: 8000
  ignore_user_in_auth: false
sync:
  url: "http://localhost:2048"
  username: "username"
  password: "password"
  interval: 300
  central_server_site_id: 1
  site_id: 2
  site_hardware_id: ""
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "omsupply-database"
auth:
  token_secret: "token-secret"
